language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - travis_retry composer self-update
  - COMPOSER_ROOT_VERSION=2.4.x-dev composer require satooshi/php-coveralls --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
