sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 7.2
  - 7.3

script:
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]]; then make test-coveralls; else make test; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]]; then composer require satooshi/php-coveralls; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]]; then php vendor/bin/php-coveralls -v; fi
