sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - wget https://phar.phpunit.de/phpunit-5.7.phar -O ./build/phpunit-5.7.phar
  - if [[ $TRAVIS_PHP_VERSION != "5.6" ]]; then COMPOSER_ROOT_VERSION=4.0 composer install; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then COMPOSER_ROOT_VERSION=4.0 composer require satooshi/php-coveralls; fi

script:
  - php ./build/phpunit-5.7.phar --coverage-clover ../clover.xml

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then php vendor/bin/coveralls -v -x clover.xml; fi
