services:
  _defaults:
    autowire: true

  ICanBoogie\Routing\PingController:
    tags:
    - { name: action_responder }
    - { name: action_alias, action: 'api:ping' }

  # Console

  console.command.cache.clear:
    class: ICanBoogie\Console\ClearCacheCommand
    tags:
    - { name: console.command, command: 'cache:clear' }

  console.command.configs.list:
    class: ICanBoogie\Console\ListConfigsCommand
    arguments:
      $style: '%console.style.table%'
    tags:
    - { name: console.command, command: 'configs' }
    - { name: console.command, command: 'configs:list' }
